#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,fish,nvim,tmux,zsh,powershell,bash" 
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
  echo $folder
  stow -D $folder
done
popd
