#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="bin,fish,nvim,tmux,zsh,powershell,bash" 
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
