require("config.lsp")
require("config.stable")
require("config.null-ls")
require("config.nvim-treesitter")
require("config.lualine")
require("config.nvim-tree")
require("config.telescope")
-- https://github.com/neovim/nvim-lspconfig/wiki/Autocompletion
require("config.cmp")
require("config.which-key")
require("config.gitsigns")
require("config.nvim-bufferline")
