local set = vim.opt

set.title = true -- Show the current file name in the titlebar
set.hidden = true
set.number = true -- Show line numbers
set.showmatch = true -- Show matching words during a search
set.hlsearch = true -- Highlight search results
set.showmode = true -- always show what mode we're currently editing in
set.incsearch = true -- Makes search act like search in modern browsers
set.smartcase = true -- Case-insensitive search
set.ignorecase = true -- Case-insensitive search
set.ruler = true -- Show a ruler at the top of the screen
set.showmode = true
set.signcolumn = "yes"
set.bg = 'dark' -- Set the background color
set.tabstop = 2
set.shiftwidth = 2
set.expandtab = true -- Expand tabs to spaces
-- set.nojoinspaces = true -- Don't join lines when pressing 'J'
set.clipboard = "unnamedplus" -- Use system clipboard
set.encoding = "UTF-8"
set.sidescrolloff = 8
set.scrolloff = 10
-- set.nowrap = true 
set.mouse = "a"
set.splitright = true
set.splitbelow = true
set.confirm = true
set.undofile = true
set.undodir = "~/.vim/undodir"
-- set.list = true
set.updatetime = 300 -- Reduce time for highlighting other references
set.redrawtime = 10000 -- Allow more time for loading syntax on large files
set.cursorline = true -- Highlight the current line
set.ttyfast = true -- Faster terminal output
set.lazyredraw = true -- Don't redraw the screen until it's actually needed
set.spelllang = "en,cjk" -- Use hunspell for spell checking
set.spellsuggest = "best,9" -- Use hunspell for spell checking
set.wildmenu = true -- Show a menu of all wildcard matches
set.wildignore = "*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx,*/node_modules/**"
